{"pr_number": 12064, "pr_title": "(CDAP-16590) Log all errors when a scheduled service failed", "pr_author": "chtyim", "pr_createdAt": "2020-04-15T18:13:56Z", "pr_url": "https://github.com/cdapio/cdap/pull/12064", "timeline": [{"oid": "5227323b5c362e4cca8e3f9771ee349914856b0d", "url": "https://github.com/cdapio/cdap/commit/5227323b5c362e4cca8e3f9771ee349914856b0d", "message": "(CDAP-16590) Log all errors when a scheduled service failed", "committedDate": "2020-04-15T18:13:35Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA0NjEzNw==", "url": "https://github.com/cdapio/cdap/pull/12064#discussion_r409046137", "body": "we can use `t` here as well", "bodyText": "we can use t here as well", "bodyHTML": "<p dir=\"auto\">we can use <code>t</code> here as well</p>", "author": "CuriousVini", "createdAt": "2020-04-15T18:26:18Z", "path": "cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java", "diffHunk": "@@ -160,15 +160,19 @@ protected final void runOneIteration() throws Exception {\n         delayMillis = runTask();\n         nonFailureStartTime = 0L;\n         failureCount = 0;\n-      } catch (Exception e) {\n-        logTaskFailure(e);\n+      } catch (Throwable t) {\n+        logTaskFailure(t);\n+        if (!(t instanceof Exception)) {\n+          throw t;\n+        }\n+        Exception e = (Exception) t;\n         if (!shouldRetry(e)) {", "originalCommit": "5227323b5c362e4cca8e3f9771ee349914856b0d", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA0OTA1Mg==", "url": "https://github.com/cdapio/cdap/pull/12064#discussion_r409049052", "bodyText": "Can't. The shouldRetry only take Exception. Technically all \"Error\" are not retryable.", "author": "chtyim", "createdAt": "2020-04-15T18:31:27Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA0NjEzNw=="}], "type": "inlineReview"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA0NjkwOA==", "url": "https://github.com/cdapio/cdap/pull/12064#discussion_r409046908", "body": "usually we do not log and throw - https://github.com/cdapio/hydrator-plugins/pull/1072#discussion_r406868886", "bodyText": "usually we do not log and throw - cdapio/hydrator-plugins#1072 (comment)", "bodyHTML": "<p dir=\"auto\">usually we do not log and throw - <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load title\" data-id=\"596116214\" data-permission-text=\"Title is private\" data-url=\"https://github.com/cdapio/hydrator-plugins/issues/1072\" data-hovercard-type=\"pull_request\" data-hovercard-url=\"/cdapio/hydrator-plugins/pull/1072/hovercard?comment_id=406868886&amp;comment_type=review_comment\" href=\"https://github.com/cdapio/hydrator-plugins/pull/1072#discussion_r406868886\">cdapio/hydrator-plugins#1072 (comment)</a></p>", "author": "CuriousVini", "createdAt": "2020-04-15T18:27:41Z", "path": "cdap-common/src/main/java/io/cdap/cdap/common/service/AbstractRetryableScheduledService.java", "diffHunk": "@@ -178,9 +182,9 @@ protected final void runOneIteration() throws Exception {\n         }\n         this.delayMillis = delayMillis;\n       }\n-    } catch (Exception e) {\n-      LOG.error(\"Aborting service {} due to non-retryable error\", getServiceName(), e);\n-      throw e;\n+    } catch (Throwable t) {\n+      LOG.error(\"Aborting service {} due to non-retryable error\", getServiceName(), t);", "originalCommit": "5227323b5c362e4cca8e3f9771ee349914856b0d", "replyToReviewId": null, "replies": [{"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA1MDMxMw==", "url": "https://github.com/cdapio/cdap/pull/12064#discussion_r409050313", "bodyText": "This is what this PR is about. When an Error is thrown up in this case, the exception is not getting log at all and the service just terminate. The guava service only log Exception.", "author": "chtyim", "createdAt": "2020-04-15T18:33:25Z", "replyToReviewId": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQwOTA0NjkwOA=="}], "type": "inlineReview"}]}